use_frameworks!

platform :ios, '8.0'

target 'HSYMethodsToolsKit_Example' do
  pod 'HSYMethodsToolsKit', :path => '../'

  target 'HSYMethodsToolsKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
